# Generated by Django 6.0.1 on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_alter_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
