# Generated by Django 6.0.1 on 2026-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_alter_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="code_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Код создан"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="sms_code",
            field=models.CharField(blank=True, max_length=6, verbose_name="SMS-код"),
        ),
    ]
