# Generated by Django 6.0.1 on 2026-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_alter_salon_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
