# Generated by Django 6.0.1 on 2026-01-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='masters_photo/', verbose_name='Фото')),
                ('start_work', models.DateField(verbose_name='Начало стажа работы')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='salon.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Мастера',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Специализация')),
                ('masters', models.ManyToManyField(related_name='specializations', to='master.master', verbose_name='Мастера')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='ScheduleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало рабочего времени')),
                ('end_time', models.TimeField(verbose_name='Окончание рабочего времени')),
                ('interval', models.PositiveSmallIntegerField(default=120, verbose_name='Интервал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно(выходной или нет)')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='master.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Расписание мастера',
                'verbose_name_plural': 'Расписания мастеров',
                'ordering': ['day'],
                'unique_together': {('master', 'day')},
            },
        ),
    ]
