# Generated by Django 5.2.8 on 2026-01-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0002_alter_salon_id'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('speciality', models.CharField(choices=[('stylist', 'стилист'), ('make-up', 'визажист'), ('nail-master', 'мастер маникюра'), ('barber', 'парикмахер')], max_length=20, verbose_name='Специальность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='masters_photo/', verbose_name='Фото мастера')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='salon.salon', verbose_name='Салон')),
                ('services', models.ManyToManyField(related_name='masters', to='service.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Мастера',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
