# Generated by Django 6.0.1 on 2026-01-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='image',
            new_name='photo',
        ),
    ]
