# Generated by Django 6.0.1 on 2026-01-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_image_master_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='masters',
        ),
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='master.specialization', verbose_name='Специализация'),
        ),
    ]
