# Generated by Django 5.2.8 on 2026-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group_services',
            field=models.CharField(choices=[('hair_services', 'Парикмахерские услуги'), ('nail_service', 'Ногтевой сервис'), ('makeup', 'Макияж')], default='makeup', max_length=100, verbose_name='Группа услуг'),
            preserve_default=False,
        ),
    ]
