# Generated by Django 6.0.1 on 2026-01-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='client',
            new_name='user',
        ),
    ]
