# Generated by Django 6.0.1 on 2026-01-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
        ("salon", "0003_alter_salon_id"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "start_time",
                    models.TimeField(verbose_name="Начало рабочего времени"),
                ),
                (
                    "end_time",
                    models.TimeField(verbose_name="Окончание рабочего времени"),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.master",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salon.salon",
                        verbose_name="Салон",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        to="service.service",
                        verbose_name="Доступные услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
                "ordering": ["date", "start_time"],
                "unique_together": {("master", "salon", "date")},
            },
        ),
    ]
