# Generated by Django 6.0.1 on 2026-01-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='image',
            new_name='photo',
        ),
    ]
