# Generated by Django 6.0.1 on 2026-01-23 15:45

import django.core.validators
import phonenumber_field.modelfields
import phonenumber_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_id_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber, django.core.validators.RegexValidator('^\\+7\\d{10}$', message='Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='Телефон'),
        ),
    ]
