# Generated by Django 6.0.1 on 2026-01-23 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^\\+79\\d{9}$', message='Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='Телефон'),
        ),
    ]
