# Generated by Django 6.0.1 on 2026-01-24 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='user',
        ),
        migrations.AddField(
            model_name='consultation',
            name='name',
            field=models.CharField(default='', verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='phone',
            field=models.CharField(default=79766334623, validators=[django.core.validators.RegexValidator('^79\\d{9}$', message='Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
